### ISSUE TITLE
What does "chunk boundary friendly" mean?

### ISSUE THREAD

**Issue by jmm** [eugeneware/replacestream#17]

**Comment by mehtaphysical** [comment]
it means that a replace should happen even if the string to be replaced is between streaming chunks of data. For example, say I do something like this

```
fs.createReadStream(path.join(__dirname, 'happybirthday.txt'))
  .pipe(replaceStream('birthday', 'earthday'))
  .pipe(process.stdout);
```

here i am trying to replace all instances of 'birthday' with 'earthday'. Let's say the first chunk of data that is available is 'happy birth' and the second chunk of data available is 'day'. In this case the replace will happen successfully, the same as it would have if the chunk contained the entire string that was to be replaced (e.g. chunk1 = 'happy' chunk2 = 'birthday')

**Comment by jmm** [comment]
Ok, thanks. Does that apply across more than 2 chunks? How does it work with regexes?

**Comment by mehtaphysical** [comment]
It does apply across multiple chunks. By default, however, the maximum match length (max_match_len) is set to 100 characters. You can increase this by adding max_match_len: x to your options:

```
replacestream('hi', 'bye', {max_match_len: 1000})
```

A string the size of max_match_len will be saved in memory so it shouldn't be set too high. max_match_len is what allows us to have a match between chunks. We are saving max_match_len characters in a string (the last max_match_len characters from the previous chunks) that we prepend to the current chunk, then attempt to find a match.

As for regex it works exactly the same except you would pass a regular expression into replacestream:

```
replacestream(/a+/, 'b')
```

**Comment by stevemao** [comment]
This explanation should probably go to README
