### ISSUE TITLE
`max_match_len` is not camelCased

### ISSUE THREAD

**Issue by stevemao** [eugeneware/replacestream#21]
other options such as `ignoreCase` and `regExpOptions` are camelCased. I think it would be better if this is consistent.

**Comment by shinnn** [comment]
+1

**Comment by eugeneware** [comment]
Hi @stevemao. `replacestream` is an [OPEN Open Source Project](https://github.com/eugeneware/replacestream/blob/master/CONTRIBUTING.md), so please put together a PR to code and the README and we'll merge it in. Question is, do we make it backwards compatible, or break semver and bump the major version. Open to either.

**Comment by stevemao** [comment]
Happy to send a PR but I wanted to know your opinion first.
I think this is probably a typo in the first place so I wouldn't worry about backwards compatibility and bump a major.

**Comment by eugeneware** [comment]
Awesome, sounds good to me!
