### ISSUE TITLE
Possible to make multiple (regex) replacements in a single pass?

### ISSUE THREAD

**Issue by dustinbolton** [eugeneware/replacestream#24]
I'd like to make multiple regex replacements in a single pass of the file. Is this possible, or do I need to run through the file multiple times? I am making several replacements on a very large file so I'm trying to find the most performant solution. Thanks!

**Comment by stevemao** [comment]
I don't understand your question. Can you elaborate?

**Comment by rodrigopolo** [comment]
@dustinbolton You can connect one stream after another, chaining. A stream only goes one time trough the file.

**Comment by stevemao** [comment]
Thanks @rodrigopolo , assume your understanding is correct, @dustinbolton you might wanna learn more about stream.https://nodejs.org/dist/latest-v5.x/docs/api/stream.html
