### ISSUE TITLE
replacing create unexecutable javascript files

### ISSUE THREAD

**Issue by EyMaddis** [eugeneware/replacestream#26]
hi,
I tried to create a simple server that replaces a string on file load and serves it (for development purposes).
I noticed that whenever it does it's magic on javascript files, it will block their execution (tested in Chrome), even though the file is completely served and the headers (content-type) are correct.

Here is my server to recreate this:

```
// jshint globalstrict:true, node:true, esnext:true
'use strict';

const koa = require('koa');
const app = koa();
const replaceStream = require('stream-replace');
const staticServe = require('koa-static');
const sendFile = require('koa-send');

app.use(function*(next) {
    const url = this.req.url;

    yield* next; // file serve

    // applying replace to javascript is breaking execution
        this.body = this.body
            .pipe(replaceStream(/{{VERSION}}/g, 'some version'));
});

app.use(staticServe('files/', {}));

const port = process.env.PORT || 8000;
app.listen(port, () => {
    console.log('server started on port', port);
});
```

it serves the files in the `files/` directory via http.

I guess that it might have something to do that the end of files are altered.

**Comment by EyMaddis** [comment]
I was able to narrow it down to only one file, I currently cannot remember which, but I would find it out if you are interested.

**Comment by stevemao** [comment]
Any info on how to replicate your problem would be useful

**Comment by EyMaddis** [comment]
It seems to break [`fabric.js`](https://github.com/kangax/fabric.js/), more explicitly:
`bower_components/fabric.js/dist/fabric.min.js`.

Chrome seems to have updated and will actually handle this now.
I now get `net::ERR_CONTENT_DECODING_FAILED` for this file, but the rest of the js files are being executed. So part of it seemed to have been a Chrome bug, but it is still breaking content encoding.

**Comment by EyMaddis** [comment]
Also breaks .png files.

**Comment by pensierinmusica** [comment]
@eugeneware @mehtaphysical Any update on this? Is this package still maintained?

**Comment by shinnn** [comment]
I created a small sample code with no koa-related libraries:

```js
'use strict';

const {readFileSync} = require('fs');

const replacestream = require('replacestream');
const simpleConcat = require('simple-concat');

// From https://github.com/eugeneware/replacestream/issues/26#issue-144857046
// Note that /{{VERSION}}/g doesn't match any part of fabric.min.js
const rs = replacestream(/{{VERSION}}/g, 'some version');

// Copied from https://github.com/kangax/fabric.js/blob/d7d88fe5c86a1e1fe7d8fbabdbc1832615605436/dist/fabric.min.js
const original = readFileSync('fabric.min.js');

simpleConcat(rs, (err, replaced) => {
  if (err) {
    console.error(err.stack);
    return;
  }

  // `true` means the original fabric.min.js isn't modified
  console.log(original.equals(replaced));
});

rs.end(original);
```

```
$ node sample.js
> true
```

As you can see, replacestream doesn't break ` fabric.min.js`. Probably other libraries you use is causing a problem that we don't maintain.

> Is this package still maintained?

 @pensierinmusica Definitely.

**Comment by pensierinmusica** [comment]
@shinnn please try with a jpeg o png file (e.g. http://www.freepngimg.com/download/lion/3-2-lion-png.png)

Does it still render correctly after `replacestream`? In my case it breaks (see https://github.com/lazd/gulp-replace/issues/91).

If so please reopen this issue, or let's open a new one for image files.

**Comment by shinnn** [comment]
@pensierinmusica [Again](https://github.com/lazd/gulp-replace/issues/91#issuecomment-328886969), as you don't disable [`buffer` option](https://github.com/gulpjs/gulp/blob/5944c1b4d4c0a9dea804bc426b936aa742792cd4/docs/API.md#optionsbuffer) and [this code path](https://github.com/lazd/gulp-replace/blob/669219160fcc611707ababac7c117325967a7e98/index.js#L22-L25) is never executed, your gulpfile doesn't invoke replacestream.

So, https://github.com/lazd/gulp-replace/issues/91 is not related to replacestream. OK?

**Comment by pensierinmusica** [comment]
Ok, thanks @shinnn for the clarification!  :)
