### ISSUE TITLE
Resulting stream is not an instance of Readable

### ISSUE THREAD

**Issue by call-a3** [eugeneware/replacestream#28]
The resulting stream uses a custom variant of streams instead of the node default implementations.
This makes it difficult to combine this transform with interfaces that use/expect the default stream implementation of node.

**Comment by shinnn** [comment]
No. [Transform stream](https://nodejs.org/api/stream.html#stream_class_stream_transform) is one of the default implementations.

**Comment by stevemao** [comment]
@call-a3 what is the real life problem you encounter?

**Comment by call-a3** [comment]
I'm using this package to mutate filestreams before passing them on to the next layer in my project. This underlying layer accepts streams but also strings and specifically-formed objects. It performs caching of a stream if necessary/possible. To determine this, it detects whether the input is I Readable from the default stream API (I'm using node v6). The streams outputted by this package don't pass that test

**Comment by shinnn** [comment]
If we drop Node v0.x support, we can safely use core Stream instead of `readable-stream` npm package.

**Comment by stevemao** [comment]
Eventually, we will. But there are many other packages that use `readable-stream`. So it won't solve your problem @call-a3  https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

**Comment by shinnn** [comment]
> https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

Yeah, I should have refer to that blog post. That is why we use `readable-stream` in this package.

@call-a3 Temporary solutions:

* https://github.com/rvagg/isstream
* https://github.com/sindresorhus/is-stream

**Comment by call-a3** [comment]
Thanks for those references. Guess I'll have to go with an is-readable-stream implementation.
