### ISSUE TITLE
Headers re-written when piping result to expressjs `res` object

### ISSUE THREAD

**Issue by Kequc** [eugeneware/replacestream#29]
I'm fetching a css file, mutating it, then piping it immediately to the browser. But the `Content-Type` header seems to be getting re-written.

```
var request = require('request');
var replacestream = require('replacestream');

// ...

        req.pipe(request({ uri: uri }))
            .pipe(replacestream('sometext', 'someothertext'))
            .pipe(res);
```

Returns an error on the client side.

```
Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: 
```

Without using `replacestream` everything turns out ok.

```
var request = require('request');
var replacestream = require('replacestream');

// ...

        req.pipe(request({ uri: uri }))
            .pipe(res);
```

It seems like the module isn't persisting stream headers. Am I right?

**Comment by shinnn** [comment]
replacestream doesn't change any `header`-related values.

```
$ git clone https://github.com/eugeneware/replacestream
$ cd replacestream
$ git grep -l header | wc -l
> 0
```

**Comment by Kequc** [comment]
Thanks for your help, could you point me in the right direction.

**Comment by shinnn** [comment]
> could you point me in the right direction.

Sorry, we can't.

👉 https://gitter.im/expressjs/express

**Comment by outluch** [comment]
I have the same problem. I pipe some `request`ed websites through replaceStream and one of them definitely lose headers in the process. When I comment out streamreplacing, my headers are in place.
