### ISSUE TITLE
Replace control chars before writing to file

### ISSUE THREAD

**Issue by ORESoftware** [eugeneware/replacestream#33]
Hi :)

I am looking to replace control chars that get written to a file. In my case, there doesn't appear to be a good way to do this except filter them out with some stream transform, hence why I am here. For some reason when writing with

`process.stdout.write `

control chars appear in the terminal as colors, etc. But when writing to a file, they show up as plain text. Must be the difference between a TTY and non-TTY, I guess.

Anyway, I have this:

`const strm = replaceStrm(/\[[0-9][0-9]m/g, '').pipe(fs.createWriteStream(logfile));`

then I call `strm.write('some-string-with-control-chars');`

And I still get control chars in my log file:

```console
before each hook finished.
	[34m ✔ [39m 'b' (1ms)
	[34m ✔ [39m 'b' (2ms)
	[34m ✔ [39m 'b' (1ms)
	[34m ✔ [39m 'b' (1ms)
```

Is my regex wrong... or am I using this library incorrectly?

thanks!

**Comment by ORESoftware** [comment]
I think my regex is wrong, this one is definitely better:

` let firstArg = String(args[0]).replace(/\[[0-9]{1,2}m/g, '').replace(/\[[0-9]{1,2};[0-9]{1,2}m/g, '');`

**Comment by ORESoftware** [comment]
oh shizbinnn

**Comment by shinnn** [comment]
This is not a replacestream issue but just a general JavaScript question. Use StackFlow instead.

> oh shizbinnn

?
